name: Backend deploy Job
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install node_modules
        run: yarn
      - name: Creating .env file
        run: |
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN}} >> .env
          echo TRADINGVIEW_EMAIL=${{ secrets.TRADINGVIEW_EMAIL}} >> .env
          echo TRADINGVIEW_PASSWORD=${{ secrets.TRADINGVIEW_PASSWORD}} >> .env
          echo OAUTH_GOOGLE_ID=${{ secrets.OAUTH_GOOGLE_ID}} >> .env
          echo OAUTH_GOOGLE_SECRET=${{ secrets.OAUTH_GOOGLE_SECRET}} >> .env
          echo OAUTH_GOOGLE_REDIRECT_URL=${{ secrets.OAUTH_GOOGLE_REDIRECT_URL}} >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI}} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET}} >> .env
          echo WEB_APPURL=${{ secrets.WEB_APPURL}} >> .env
      - name: Build the project
        run: yarn build
      - name: Listing files and remove node_modules
        run: |
          ls -a
          rm -rf node_modules
      - name: Deploy with rsync
        run: |
          rsync -avz * root@${{ secrets.SSH_HOST }}:./app
          rsync -avz .env root@${{ secrets.SSH_HOST }}:./app
      - name: Executing cmd on remote
        run: |
          ssh -y root@${{ secrets.SSH_HOST }} 'cd app && yarn'
          echo 'Installing pm2'
          ssh -y root@${{ secrets.SSH_HOST }} 'yarn global add pm2'
          echo 'Starting pm2 app'
          ssh -y root@${{ secrets.SSH_HOST }} 'cd ~/app && pm2 restart candly'
          ssh -y root@${{ secrets.SSH_HOST }} 'pm2 startup systemd'
          ssh -y root@${{ secrets.SSH_HOST }} 'pm2 save'
      - name: Setup finish
        run: echo "Setup Finished!"
